
// INSERT HERE YOUR CUSTOM CONSTANTS




// START CRUD CONSTANTS

// USER
export const CHANGEPASSWORD_USER_SUCCESS = "CHANGEPASSWORD_USER_SUCCESS";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const LIST_USER_SUCCESS = "LIST_USER_SUCCESS";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";

// BRANDS
export const CREATE_BRANDS_SUCCESS = "CREATE_BRANDS_SUCCESS";
export const DELETE_BRANDS_SUCCESS = "DELETE_BRANDS_SUCCESS";
export const GET_BRANDS_SUCCESS = "GET_BRANDS_SUCCESS";
export const LIST_BRANDS_SUCCESS = "LIST_BRANDS_SUCCESS";
export const UPDATE_BRANDS_SUCCESS = "UPDATE_BRANDS_SUCCESS";

// DEALERBRANDS
export const CREATE_DEALERBRANDS_SUCCESS = "CREATE_DEALERBRANDS_SUCCESS";
export const DELETE_DEALERBRANDS_SUCCESS = "DELETE_DEALERBRANDS_SUCCESS";
export const FINDBYBRANDID_DEALERBRANDS_SUCCESS = "FINDBYBRANDID_DEALERBRANDS_SUCCESS";
export const GET_DEALERBRANDS_SUCCESS = "GET_DEALERBRANDS_SUCCESS";
export const LIST_DEALERBRANDS_SUCCESS = "LIST_DEALERBRANDS_SUCCESS";
export const UPDATE_DEALERBRANDS_SUCCESS = "UPDATE_DEALERBRANDS_SUCCESS";

// DEALERSHIP
export const CREATE_DEALERSHIP_SUCCESS = "CREATE_DEALERSHIP_SUCCESS";
export const DELETE_DEALERSHIP_SUCCESS = "DELETE_DEALERSHIP_SUCCESS";
export const FINDBYBRANDS_DEALERSHIP_SUCCESS = "FINDBYBRANDS_DEALERSHIP_SUCCESS";
export const GET_DEALERSHIP_SUCCESS = "GET_DEALERSHIP_SUCCESS";
export const LIST_DEALERSHIP_SUCCESS = "LIST_DEALERSHIP_SUCCESS";
export const UPDATE_DEALERSHIP_SUCCESS = "UPDATE_DEALERSHIP_SUCCESS";

// STATE
export const CREATE_STATE_SUCCESS = "CREATE_STATE_SUCCESS";
export const DELETE_STATE_SUCCESS = "DELETE_STATE_SUCCESS";
export const GET_STATE_SUCCESS = "GET_STATE_SUCCESS";
export const LIST_STATE_SUCCESS = "LIST_STATE_SUCCESS";
export const UPDATE_STATE_SUCCESS = "UPDATE_STATE_SUCCESS";

// END CRUD CONSTANTS

// USER
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
export const CHANGE_PASSWORD_ADMIN_SUCCESS = "CHANGE_PASSWORD_ADMIN_SUCCESS";
